=== johnhooks/lolly/resources/schemas/http-logging-config.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "https://dozuki.zip/schemas/http-logging-config.json",
    "title": "Dozuki log configuration.",
    "description": "Configuration for the Dozuki WordPress logging plugin.",
    "type": "object",
    "properties": {
        "version": {
            "description": "The config schema version number.",
            "type": "number"
        },
        "enabled": {
            "description": "Whether the Dozuki logger is enabled.",
            "type": "boolean"
        },
        "wp_rest_logging_enabled": {
            "description": "Whether the WordPress REST API logging feature is enabled.",
            "type": "boolean"
        },
        "wp_http_client_logging_enabled": {
            "description": "Whether the WordPress HTTP client logging feature is enabled.",
            "type": "boolean"
        },
        "http_redactions_enabled": {
            "description": "Whether the HTTP logging redaction feature is enabled.",
            "type": "boolean"
        },
        "http_whitelist_enabled": {
            "description": "Whether the HTTP logging whitelist feature is enabled.",
            "type": "boolean"
        },
        "http_redactions": {
            "description": "The HTTP message redaction configuration.",
            "type": "array",
            "items": {
                "title": "HTTP redaction set.",
                "description": "A configuration of properties to redact from HTTP messages.",
                "type": "object",
                "properties": {
                    "host": {
                        "description": "The URL host value to match for redaction target.",
                        "type": "string"
                    },
                    "paths": {
                        "description": "The URL path redaction set.",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "path": {
                                    "description": "The URL path value to match for redaction target.",
                                    "type": "string"
                                },
                                "redactions": {
                                    "description": "The redaction set.",
                                    "type": "array",
                                    "items": {
                                        "title": "Redaction item.",
                                        "description": "The target property redaction data.",
                                        "type": "object",
                                        "properties": {
                                            "type": {
                                                "description": "The HTTP redaction type.",
                                                "type": "string",
                                                "enum": ["*", "query", "header", "request", "response"]
                                            },
                                            "value": {
                                                "description": "The value to match a redaction target property.",
                                                "type": "string"
                                            },
                                            "remove": {
                                                "description": "Whether the property should be entirely removed from the target.",
                                                "type": "boolean"
                                            }
                                        },
                                        "required": [
                                            "type",
                                            "value"
                                        ]
                                    }
                                },
                                "glob": {
                                    "description": "Whether to glob match the URL path.",
                                    "type": "boolean"
                                }
                            },
                            "required": [
                                "path",
                                "redactions"
                            ]
                        }
                    }
                }
            }
        },
        "http_whitelist": {
            "description": "The HTTP message whitelisting configuration.",
            "type": "array",
            "items": {
                "title": "HTTP whitelist set.",
                "description": "A configuration URLs to whitelist for HTTP message logging.",
                "type": "object",
                "properties": {
                    "host": {
                        "description": "The URL host value to match for whitelist target.",
                        "type": "string"
                    },
                    "paths": {
                        "description": "The URL path whitelist set.",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "path": {
                                    "description": "The URL path value to match for a whitelist target.",
                                    "type": "string"
                                },
                                "glob": {
                                    "description": "Whether to glob match the URL path.",
                                    "type": "boolean"
                                }
                            },
                            "required": [
                                "path"
                            ]
                        }
                    },
                    "glob": {
                        "description": "Whether to glob match the URL host.",
                        "type": "boolean"
                    }
                },
                "required": [
                    "host"
                ]
            }
        }
    },
    "required": [
        "version",
        "enabled",
        "http_redactions_enabled",
        "http_whitelist_enabled",
        "wp_rest_logging_enabled",
        "wp_http_client_logging_enabled",
        "http_redactions",
        "http_whitelist"
    ]
}

=== johnhooks/lolly/config/default-logging-config.json
{
    "$schema": "https://dozuki.zip/schemas/http-logging-config.json",
    "version": 1,
    "enabled": false,
    "http_redactions_enabled": true,
    "http_whitelist_enabled": false,
    "wp_rest_logging_enabled": true,
    "wp_http_client_logging_enabled": true,
    "http_redactions": [
        {
            "host": "*",
            "paths": [
                {
                    "path": "*",
                    "redactions": [
                        {"type": "*", "value": "password"},
                        {"type": "*", "value": "password_confirm"},
                        {"type": "*", "value": "password_confirmation"},
                        {"type": "*", "value": "api_key"},
                        {"type": "*", "value": "apikey"},
                        {"type": "*", "value": "hash"},
                        {"type": "header", "value": "cookie", "remove": true},
                        {"type": "header", "value": "authorization", "remove": true}
                    ]
                }
            ]
        },
        {
            "host": "wordpress.org",
            "paths": [
                {
                    "path": "/news/feed/",
                    "redactions": [
                        {"type": "response", "value": "*", "remove": true}
                    ]
                }
            ]
        },
        {
            "host": "api.wordpress.org",
            "paths": [
                {
                    "path": "/core/checksums/",
                    "redactions": [
                        {"type": "response", "value": "*", "remove": true}
                    ],
                    "glob": true
                },
                {
                    "path": "/core/version-check/",
                    "redactions": [
                        {"type": "query", "value": "*", "remove": true},
                        {"type": "response", "value": "*", "remove": true}
                    ],
                    "glob": true
                },
                {
                    "path": "/plugins/info/",
                    "redactions": [
                        {"type": "response", "value": "*", "remove": true}
                    ],
                    "glob": true
                },
                {
                    "path": "/plugins/update-check/",
                    "redactions": [
                        {"type": "response", "value": "*", "remove": true}
                    ],
                    "glob": true
                },
                {
                    "path": "/themes/info/",
                    "redactions": [
                        {"type": "response", "value": "*", "remove": true}
                    ],
                    "glob": true
                },
                {
                    "path": "/themes/update-check/",
                    "redactions": [
                        {"type": "response", "value": "*", "remove": true}
                    ],
                    "glob": true
                },
                {
                    "path": "/translations/core/",
                    "redactions": [
                        {"type": "response", "value": "*", "remove": true}
                    ],
                    "glob": true
                }
            ]
        },
        {
            "host": "planet.wordpress.org",
            "paths": [
                {
                    "path": "/feed/",
                    "redactions": [
                        {"type": "response", "value": "*", "remove": true}
                    ]
                }
            ]
        }
    ],
    "http_whitelist": []
}
